'use client'
import {useEffect,useState} from 'react'
import {supabase} from '@/lib/supabase'
import {AdminDenied,AdminFrame,useAdminGuard} from '../admin-shared'
type Team={id:string;name:string;season_id?:string;captain_player_id:string|null};type Player={id:string;team_id:string|null;full_name:string;official_tee_color:string|null}
const teeOptions=[{value:'',label:'Not Set'},{value:'turquoise',label:'Forward Tees'},{value:'red',label:'Senior Tees'},{value:'yellow',label:'Middle Tees'},{value:'blue',label:'Back Tees'},{value:'black',label:'Tips'}]
export default function TeamsAdmin(){const guard=useAdminGuard();const [teams,setTeams]=useState<Team[]>([]),[players,setPlayers]=useState<Player[]>([]),[newNames,setNewNames]=useState<Record<string,string>>({}),[msg,setMsg]=useState('')
 async function load(){if(!guard.admin)return;const {data:s}=await supabase.from('seasons').select('id').eq('is_active',true).eq('is_closed',false).limit(1).maybeSingle();const {data:t}=s?.id?await supabase.from('teams').select('id,name,season_id,captain_player_id').eq('season_id',s.id).eq('is_active',true).order('name'):await supabase.from('teams').select('id,name,season_id,captain_player_id').eq('is_active',true).order('name');setTeams((t||[]) as Team[]);const ids=(t||[]).map(x=>x.id);const {data:p}=ids.length?await supabase.from('players').select('id,team_id,full_name,official_tee_color').in('team_id',ids).eq('is_active',true).order('created_at'):({data:[]} as any);setPlayers((p||[]) as Player[])}
 useEffect(()=>{load()},[guard.admin])
 async function renameTeam(id:string,current:string){const name=window.prompt('Team name',current)?.trim();if(!name||name===current)return;const {error}=await supabase.from('teams').update({name}).eq('id',id);setMsg(error?error.message:'Team name updated.');if(!error)load()}
 async function renamePlayer(id:string,current:string){const full_name=window.prompt('Player name',current)?.trim();if(!full_name||full_name===current)return;const {error}=await supabase.from('players').update({full_name}).eq('id',id);setMsg(error?error.message:'Player updated.');if(!error)load()}
 async function tee(id:string,color:string){const {error}=await supabase.from('players').update({official_tee_color:color||null}).eq('id',id);setMsg(error?error.message:'Official tee box updated.');if(!error)load()}
 async function setCaptain(team:Team,playerId:string){if(playerId&&!players.some(p=>p.id===playerId&&p.team_id===team.id)){setMsg('That player is not on this team.');return}const {error}=await supabase.from('teams').update({captain_player_id:playerId||null}).eq('id',team.id);setMsg(error?error.message:(playerId?'Team captain updated.':'Team captain cleared.'));if(!error)load()}
 async function remove(id:string,name:string){if(!window.confirm(`Remove ${name} from the active roster? Past season history will remain saved.`))return;const team=teams.find(t=>t.captain_player_id===id);if(team){const {error:captainError}=await supabase.from('teams').update({captain_player_id:null}).eq('id',team.id);if(captainError){setMsg(captainError.message);return}}const {error}=await supabase.from('players').update({is_active:false}).eq('id',id);setMsg(error?error.message:'Player removed from active roster.');if(!error)load()}
 async function add(team:Team){const full_name=(newNames[team.id]||'').trim();if(!full_name)return;const {error}=await supabase.from('players').insert({season_id:team.season_id,team_id:team.id,full_name,is_active:true});setMsg(error?error.message:`${full_name} added to ${team.name}.`);if(!error){setNewNames(v=>({...v,[team.id]:''}));load()}}
 if(!guard.ready || !guard.admin)return <AdminDenied {...guard}/>;return <AdminFrame title="Players & Teams" description="Manage active teams, player names, tee boxes, and rosters.">{msg&&<p className="message">{msg}</p>}<div className="admin-team-grid">{teams.map(t=>{const teamPlayers=players.filter(p=>p.team_id===t.id).sort((a,b)=>(a.id===t.captain_player_id?-1:b.id===t.captain_player_id?1:a.full_name.localeCompare(b.full_name)));return <div className="card admin-team-card" key={t.id}><div className="admin-team-header"><div><div className="eyebrow">Active Team</div><h3>{t.name}</h3><label className="admin-captain-control-v1357">Team Captain<select value={t.captain_player_id||''} onChange={e=>setCaptain(t,e.target.value)}><option value="">Not Set</option>{teamPlayers.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></label></div><button className="btn secondary small" onClick={()=>renameTeam(t.id,t.name)}>Edit Team Name</button></div><div className="admin-roster-head"><span>Player</span><span>Official Tee Box</span><span>Actions</span></div><div className="admin-roster-list">{teamPlayers.map(p=><div className="admin-roster-row" key={p.id}><div className="admin-player-name"><strong>{p.full_name}{p.id===t.captain_player_id&&<span className="captain-mark-v1357"> (C)</span>}</strong></div><div className="admin-tee-control"><select className="tee-select" value={p.official_tee_color||''} onChange={e=>tee(p.id,e.target.value)}>{teeOptions.map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</select></div><div className="admin-player-actions"><button className="btn secondary small" onClick={()=>renamePlayer(p.id,p.full_name)}>Edit Name</button><button className="btn danger small" onClick={()=>remove(p.id,p.full_name)}>Remove</button></div></div>)}</div><div className="admin-add-player"><div><strong>Add Player</strong><p className="muted">Add someone to this active roster.</p></div><div className="add-player"><input placeholder="Player name" value={newNames[t.id]||''} onChange={e=>setNewNames(v=>({...v,[t.id]:e.target.value}))}/><button className="btn small" onClick={()=>add(t)}>Add Player</button></div></div></div>})}</div></AdminFrame>}
