'use client'
import {FormEvent,useEffect,useMemo,useState} from 'react'
import {supabase} from '@/lib/supabase'
import {AdminDenied,AdminFrame,useAdminGuard} from '../admin-shared'
type Team={id:string;name:string};type Booking={id:string;kind:'personal'|'league'|'blocked';status:string;user_id:string|null;team_id:string|null;title:string|null;start_at:string;end_at:string}
const pad=(n:number)=>String(n).padStart(2,'0');const easternStamp=(date:string,hour:number)=>`${date} ${pad(hour)}:00:00 America/New_York`
const fmtDate=(v:string)=>new Date(v).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})
const fmtTime=(v:string)=>new Date(v).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})
export default function SimulatorAdmin(){const guard=useAdminGuard();const [teams,setTeams]=useState<Team[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[names,setNames]=useState<Record<string,string>>({}),[teamId,setTeamId]=useState(''),[date,setDate]=useState(''),[hour,setHour]=useState(18),[duration,setDuration]=useState(2),[blockTitle,setBlockTitle]=useState(''),[blockDate,setBlockDate]=useState(''),[blockHour,setBlockHour]=useState(12),[blockDuration,setBlockDuration]=useState(1),[msg,setMsg]=useState(''),[range,setRange]=useState<'7'|'30'|'all'>('7'),[page,setPage]=useState(0),[jumpDate,setJumpDate]=useState('')
 async function load(){if(!guard.admin)return;const {data:s}=await supabase.from('seasons').select('id').eq('is_active',true).eq('is_closed',false).limit(1).maybeSingle();const {data:t}=s?.id?await supabase.from('teams').select('id,name').eq('season_id',s.id).eq('is_active',true).order('name'):await supabase.from('teams').select('id,name').eq('is_active',true).order('name');setTeams((t||[]) as Team[]);if(t?.[0]&&!teamId)setTeamId(t[0].id);const {data:b,error}=await supabase.from('bookings').select('id,kind,status,user_id,team_id,title,start_at,end_at').eq('status','active').gte('end_at',new Date().toISOString()).order('start_at').limit(500);if(error){setMsg(error.message);return}const rows=(b||[]) as Booking[];setBookings(rows);const ids=[...new Set(rows.map(x=>x.user_id).filter(Boolean))] as string[];if(ids.length){const {data:p}=await supabase.from('profiles').select('id,full_name,email').in('id',ids);setNames(Object.fromEntries((p||[]).map(x=>[x.id,x.full_name||x.email||'Player'])))}else setNames({})}
 useEffect(()=>{load()},[guard.admin])
 useEffect(()=>{setPage(0)},[range,jumpDate])
 async function addLeague(e:FormEvent){e.preventDefault();const t=teams.find(x=>x.id===teamId);const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('bookings').insert({kind:'league',team_id:teamId,title:`${t?.name||'Team'} – League Round`,start_at:easternStamp(date,hour),end_at:easternStamp(date,hour+duration),created_by:user?.id});setMsg(error?error.message:'League reservation added.');if(!error)load()}
 async function addBlock(e:FormEvent){e.preventDefault();const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('bookings').insert({kind:'blocked',title:blockTitle||'Unavailable',start_at:easternStamp(blockDate,blockHour),end_at:easternStamp(blockDate,blockHour+blockDuration),created_by:user?.id});setMsg(error?error.message:'Blocked time added.');if(!error)load()}
 const who=(b:Booking)=>b.kind==='personal'?(b.user_id?names[b.user_id]||'Player reservation':'Player reservation'):b.kind==='league'?(teams.find(t=>t.id===b.team_id)?.name||b.title||'League reservation'):(b.title||'Blocked / unavailable')
 const filtered=useMemo(()=>{const now=new Date();const limit=new Date(now);if(range==='7')limit.setDate(limit.getDate()+7);if(range==='30')limit.setDate(limit.getDate()+30);return bookings.filter(b=>{const start=new Date(b.start_at);if(jumpDate){const key=start.toLocaleDateString('en-CA');if(key!==jumpDate)return false}if(range!=='all'&&start>limit)return false;return true})},[bookings,range,jumpDate])
 const pageSize=10,totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)),safePage=Math.min(page,totalPages-1),visible=filtered.slice(safePage*pageSize,safePage*pageSize+pageSize)
 if(!guard.ready || !guard.admin)return <AdminDenied {...guard}/>
 return <AdminFrame title="Simulator" description="Add league or blocked time, then review upcoming simulator bookings in a compact schedule.">{msg&&<p className="message">{msg}</p>}
 <section><div className="section-title"><h2>Add Simulator Time</h2></div><div className="grid-2"><div className="card"><h3>Add League Reservation</h3><form onSubmit={addLeague} className="form-grid single"><label className="field">Team<select value={teamId} onChange={e=>setTeamId(e.target.value)}>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="field">Date<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field">Start Time<select value={hour} onChange={e=>setHour(Number(e.target.value))}>{Array.from({length:15},(_,i)=>i+7).map(h=><option key={h} value={h}>{new Intl.DateTimeFormat('en-US',{hour:'numeric'}).format(new Date(2020,0,1,h))}</option>)}</select></label><label className="field">Length<select value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value={1}>1 hour</option><option value={2}>2 hours</option><option value={3}>3 hours</option></select></label><button className="btn">Add League Reservation</button></form></div><div className="card"><h3>Block Simulator Time</h3><form onSubmit={addBlock} className="form-grid single"><label className="field">Reason<input value={blockTitle} onChange={e=>setBlockTitle(e.target.value)} placeholder="Unavailable"/></label><label className="field">Date<input required type="date" value={blockDate} onChange={e=>setBlockDate(e.target.value)}/></label><label className="field">Start Time<select value={blockHour} onChange={e=>setBlockHour(Number(e.target.value))}>{Array.from({length:15},(_,i)=>i+7).map(h=><option key={h} value={h}>{new Intl.DateTimeFormat('en-US',{hour:'numeric'}).format(new Date(2020,0,1,h))}</option>)}</select></label><label className="field">Length<select value={blockDuration} onChange={e=>setBlockDuration(Number(e.target.value))}><option value={1}>1 hour</option><option value={2}>2 hours</option><option value={3}>3 hours</option></select></label><button className="btn">Block Time</button></form></div></div></section>
 <section><div className="section-title"><div><h2>Upcoming Simulator Bookings</h2><p className="muted">Use the date and range controls so the booking list stays short as reservations grow.</p></div><button className="btn secondary small" onClick={load}>Refresh</button></div><div className="card simulator-booking-browser-v1238"><div className="sim-booking-controls-v1238"><div className="sim-range-buttons-v1238"><button className={range==='7'?'active':''} onClick={()=>setRange('7')}>Next 7 Days</button><button className={range==='30'?'active':''} onClick={()=>setRange('30')}>Next 30 Days</button><button className={range==='all'?'active':''} onClick={()=>setRange('all')}>All Upcoming</button></div><label className="field sim-jump-date-v1238">Specific Date<input type="date" value={jumpDate} onChange={e=>setJumpDate(e.target.value)}/></label>{jumpDate&&<button className="btn secondary small" onClick={()=>setJumpDate('')}>Clear Date</button>}</div><div className="sim-booking-summary-v1238"><strong>{filtered.length} booking{filtered.length===1?'':'s'}</strong><span>{filtered.length?`Showing ${safePage*pageSize+1}–${Math.min((safePage+1)*pageSize,filtered.length)}`:'Nothing scheduled in this view'}</span></div><div className="table-wrap"><table className="sim-booking-table-v1238"><thead><tr><th>Date</th><th>Time</th><th>Reserved By / Reason</th><th>Type</th></tr></thead><tbody>{visible.length===0?<tr><td colSpan={4}>No upcoming reservations in this view.</td></tr>:visible.map(b=><tr key={b.id}><td><strong>{fmtDate(b.start_at)}</strong></td><td>{fmtTime(b.start_at)} – {fmtTime(b.end_at)}</td><td><strong>{who(b)}</strong></td><td><span className={`sim-kind-pill-v1238 ${b.kind}`}>{b.kind==='personal'?'Player':b.kind==='league'?'League':'Blocked'}</span></td></tr>)}</tbody></table></div>{totalPages>1&&<div className="sim-pagination-v1238"><button className="btn secondary small" disabled={safePage===0} onClick={()=>setPage(p=>Math.max(0,p-1))}>← Previous</button><span>Page {safePage+1} of {totalPages}</span><button className="btn secondary small" disabled={safePage>=totalPages-1} onClick={()=>setPage(p=>Math.min(totalPages-1,p+1))}>Next →</button></div>}</div></section>
 </AdminFrame>}
