'use client'

import { FormEvent, useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'
import MonthlySetup from './monthly-setup'
import WeeklyScoring from './weekly-scoring'
import Week4Cup from './week4-cup'
import AdminAnnouncements from './announcements'

type Profile={id:string;full_name:string;email:string|null;status:string;booking_enabled:boolean;created_at:string}
type Team={id:string;name:string;season_id?:string}
type Player={id:string;team_id:string|null;full_name:string;is_active:boolean;official_tee_color:string|null}
const pad=(n:number)=>String(n).padStart(2,'0')
function easternStamp(date:string,hour:number){return `${date} ${pad(hour)}:00:00 America/New_York`}

export default function AdminPage(){
 const [admin,setAdmin]=useState(false);const [ready,setReady]=useState(false);const [seasonId,setSeasonId]=useState('');const [requests,setRequests]=useState<Profile[]>([]);const [approved,setApproved]=useState<Profile[]>([]);const [teams,setTeams]=useState<Team[]>([]);const [players,setPlayers]=useState<Player[]>([]);const [msg,setMsg]=useState('')
 const [teamId,setTeamId]=useState('');const [newPlayerNames,setNewPlayerNames]=useState<Record<string,string>>();const [date,setDate]=useState('');const [hour,setHour]=useState(18);const [duration,setDuration]=useState(2);const [blockTitle,setBlockTitle]=useState('');const [blockDate,setBlockDate]=useState('');const [blockHour,setBlockHour]=useState(12);const [blockDuration,setBlockDuration]=useState(1)
 async function load(){const {data:u}=await supabase.auth.getUser();if(!u.user){setReady(true);return};const {data:p}=await supabase.from('profiles').select('role,status').eq('id',u.user.id).maybeSingle();const ok=p?.role==='admin'&&p?.status==='approved';setAdmin(ok);if(ok){const {data:r}=await supabase.from('profiles').select('id,full_name,email,status,booking_enabled,created_at').in('status',['pending','denied','suspended']).order('created_at');setRequests((r||[]) as Profile[]);const {data:a}=await supabase.from('profiles').select('id,full_name,email,status,booking_enabled,created_at').eq('status','approved').neq('role','admin').order('full_name');setApproved((a||[]) as Profile[]);const {data:s}=await supabase.from('seasons').select('id').eq('is_active',true).eq('is_closed',false).limit(1).maybeSingle();if(s?.id)setSeasonId(s.id);const {data:t}=s?await supabase.from('teams').select('id,name,season_id').eq('season_id',s.id).eq('is_active',true).order('name'):await supabase.from('teams').select('id,name,season_id').eq('is_active',true).order('name');setTeams((t||[]) as Team[]);const ids=(t||[]).map(x=>x.id);const {data:pl}=ids.length?await supabase.from('players').select('id,team_id,full_name,is_active,official_tee_color').in('team_id',ids).eq('is_active',true).order('created_at'):({data:[]} as any);setPlayers((pl||[]) as Player[]);if(t?.[0]&&!teamId)setTeamId(t[0].id)}setReady(true)}
 useEffect(()=>{load()},[])
 async function setStatus(id:string,status:'approved'|'denied'){const {error}=await supabase.from('profiles').update({status,booking_enabled:status==='approved'}).eq('id',id);setMsg(error?error.message:`Account ${status}.`);if(!error)load()}
 async function suspendUser(id:string){const {error}=await supabase.from('profiles').update({status:'suspended',booking_enabled:false}).eq('id',id);setMsg(error?error.message:'Booking access suspended.');if(!error)load()}


 const teeOptions=[
  {value:'',label:'Not Set'},
  {value:'turquoise',label:'Forward Tees'},
  {value:'red',label:'Senior Tees'},
  {value:'yellow',label:'Middle Tees'},
  {value:'blue',label:'Back Tees'},
  {value:'black',label:'Tips'}
 ]
 async function setPlayerTee(id:string,color:string){const {error}=await supabase.from('players').update({official_tee_color:color||null}).eq('id',id);setMsg(error?error.message:'Official tee box updated.');if(!error)load()}

 async function renameTeam(id:string,current:string){const name=window.prompt('Team name',current)?.trim();if(!name||name===current)return;const {error}=await supabase.from('teams').update({name}).eq('id',id);setMsg(error?error.message:'Team name updated.');if(!error)load()}
 async function renamePlayer(id:string,current:string){const full_name=window.prompt('Player name',current)?.trim();if(!full_name||full_name===current)return;const {error}=await supabase.from('players').update({full_name}).eq('id',id);setMsg(error?error.message:'Player updated.');if(!error)load()}
 async function removePlayer(id:string,name:string){if(!window.confirm(`Remove ${name} from the active roster? Past season history will remain saved.`))return;const {error}=await supabase.from('players').update({is_active:false}).eq('id',id);setMsg(error?error.message:'Player removed from active roster.');if(!error)load()}
 async function addPlayer(team:Team){const full_name=(newPlayerNames?.[team.id]||'').trim();if(!full_name)return;const {error}=await supabase.from('players').insert({season_id:team.season_id,team_id:team.id,full_name,is_active:true});setMsg(error?error.message:`${full_name} added to ${team.name}.`);if(!error){setNewPlayerNames(v=>({...v,[team.id]:''}));load()}}
 async function addLeague(e:FormEvent){e.preventDefault();setMsg('');const t=teams.find(x=>x.id===teamId);const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('bookings').insert({kind:'league',team_id:teamId,title:`${t?.name||'Team'} – League Round`,start_at:easternStamp(date,hour),end_at:easternStamp(date,hour+duration),created_by:u.user?.id});setMsg(error?error.message:'League reservation added.')}
 async function addBlock(e:FormEvent){e.preventDefault();const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('bookings').insert({kind:'blocked',title:blockTitle||'Unavailable',start_at:easternStamp(blockDate,blockHour),end_at:easternStamp(blockDate,blockHour+blockDuration),created_by:u.user?.id});setMsg(error?error.message:'Blocked time added.')}
 if(!ready)return <p>Loading…</p>
 if(!admin)return <div className="card"><h1>Admin</h1><p>This area is available only to approved administrators.</p></div>
 return <><section className="hero"><div className="eyebrow">Administration</div><h1>Simulator & League Admin</h1><p>Approve accounts, schedule league rounds, and block simulator time.</p></section>{msg&&<p className="message">{msg}</p>}
 <section><div className="section-title"><h2>Account Approvals</h2></div>{requests.length===0?<div className="card">No pending, denied, or suspended accounts.</div>:<div className="card table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Status</th><th>Action</th></tr></thead><tbody>{requests.map(p=><tr key={p.id}><td>{p.full_name||'—'}</td><td>{p.email}</td><td>{p.status}</td><td className="actions"><button className="btn small" onClick={()=>setStatus(p.id,'approved')}>Approve</button><button className="btn danger small" onClick={()=>setStatus(p.id,'denied')}>Deny</button></td></tr>)}</tbody></table></div>}</section>
 <AdminAnnouncements/>
 <section><div className="section-title"><h2>Approved Users</h2></div>{approved.length===0?<div className="card">No approved non-admin users yet.</div>:<div className="card table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Booking</th><th>Action</th></tr></thead><tbody>{approved.map(p=><tr key={p.id}><td>{p.full_name||'—'}</td><td>{p.email}</td><td>{p.booking_enabled?'Enabled':'Disabled'}</td><td><button className="btn danger small" onClick={()=>suspendUser(p.id)}>Suspend</button></td></tr>)}</tbody></table></div>}</section>
 <section className="admin-rosters-section"><div className="section-title"><div><h2>Teams & Rosters</h2><p className="muted">Edit player names, set official tee boxes, add players, or remove players from the active roster.</p></div></div><div className="admin-team-grid">{teams.map(t=><div className="card admin-team-card" key={t.id}><div className="admin-team-header"><div><div className="eyebrow">Active Team</div><h3>{t.name}</h3></div><button className="btn secondary small" onClick={()=>renameTeam(t.id,t.name)}>Edit Team Name</button></div><div className="admin-roster-head"><span>Player</span><span>Official Tee Box</span><span>Actions</span></div><div className="admin-roster-list">{players.filter(p=>p.team_id===t.id).map(p=><div className="admin-roster-row" key={p.id}><div className="admin-player-name"><strong>{p.full_name}</strong></div><div className="admin-tee-control"><select className="tee-select" aria-label={`Official tee box for ${p.full_name}`} value={p.official_tee_color||''} onChange={e=>setPlayerTee(p.id,e.target.value)}>{teeOptions.map(o=><option key={o.value||'none'} value={o.value}>{o.label}</option>)}</select></div><div className="admin-player-actions"><button className="btn secondary small" onClick={()=>renamePlayer(p.id,p.full_name)}>Edit Name</button><button className="btn danger small" onClick={()=>removePlayer(p.id,p.full_name)}>Remove</button></div></div>)}</div><div className="admin-add-player"><div><strong>Add Player</strong><p className="muted">Adds the player to {t.name} for the active season.</p></div><div className="add-player"><input aria-label={`New player for ${t.name}`} placeholder="Player name" value={newPlayerNames?.[t.id]||''} onChange={e=>setNewPlayerNames(v=>({...v,[t.id]:e.target.value}))}/><button className="btn small" onClick={()=>addPlayer(t)}>Add Player</button></div></div></div>)}</div></section>
 <MonthlySetup seasonId={seasonId} teams={teams} players={players}/>
 <WeeklyScoring seasonId={seasonId} teams={teams}/>
 <Week4Cup seasonId={seasonId} teams={teams}/>
 <div className="grid admin-grid"><div className="card"><h2>Add League Reservation</h2><p className="muted">These display the team name on the public booking calendar.</p><form onSubmit={addLeague} className="form-grid single"><label className="field">Team<select value={teamId} onChange={e=>setTeamId(e.target.value)}>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="field">Date<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field">Start<select value={hour} onChange={e=>setHour(Number(e.target.value))}>{Array.from({length:14},(_,i)=>i+7).map(h=><option key={h} value={h}>{new Intl.DateTimeFormat('en-US',{hour:'numeric'}).format(new Date(2020,0,1,h))}</option>)}</select></label><label className="field">Length<select value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value={1}>1 hour</option><option value={2}>2 hours</option><option value={3}>3 hours</option></select></label><button className="btn">Add League Reservation</button></form></div>
 <div className="card"><h2>Block Simulator Time</h2><p className="muted">Use for maintenance, events, or other unavailable periods.</p><form onSubmit={addBlock} className="form-grid single"><label className="field">Label<input placeholder="Unavailable" value={blockTitle} onChange={e=>setBlockTitle(e.target.value)}/></label><label className="field">Date<input type="date" required value={blockDate} onChange={e=>setBlockDate(e.target.value)}/></label><label className="field">Start<select value={blockHour} onChange={e=>setBlockHour(Number(e.target.value))}>{Array.from({length:14},(_,i)=>i+7).map(h=><option key={h} value={h}>{new Intl.DateTimeFormat('en-US',{hour:'numeric'}).format(new Date(2020,0,1,h))}</option>)}</select></label><label className="field">Length<select value={blockDuration} onChange={e=>setBlockDuration(Number(e.target.value))}><option value={1}>1 hour</option><option value={2}>2 hours</option><option value={3}>3 hours</option></select></label><button className="btn">Block Time</button></form></div></div>
 </>
}
