'use client'

import { FormEvent, useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'

type Profile={id:string;full_name:string;email:string|null;status:string;booking_enabled:boolean;created_at:string}
type Team={id:string;name:string}
const pad=(n:number)=>String(n).padStart(2,'0')
function easternStamp(date:string,hour:number){return `${date} ${pad(hour)}:00:00 America/New_York`}

export default function AdminPage(){
 const [admin,setAdmin]=useState(false);const [ready,setReady]=useState(false);const [requests,setRequests]=useState<Profile[]>([]);const [teams,setTeams]=useState<Team[]>([]);const [msg,setMsg]=useState('')
 const [teamId,setTeamId]=useState('');const [date,setDate]=useState('');const [hour,setHour]=useState(18);const [duration,setDuration]=useState(2);const [blockTitle,setBlockTitle]=useState('');const [blockDate,setBlockDate]=useState('');const [blockHour,setBlockHour]=useState(12);const [blockDuration,setBlockDuration]=useState(1)
 async function load(){const {data:u}=await supabase.auth.getUser();if(!u.user){setReady(true);return};const {data:p}=await supabase.from('profiles').select('role,status').eq('id',u.user.id).maybeSingle();const ok=p?.role==='admin'&&p?.status==='approved';setAdmin(ok);if(ok){const {data:r}=await supabase.from('profiles').select('id,full_name,email,status,booking_enabled,created_at').in('status',['pending','denied','suspended']).order('created_at');setRequests((r||[]) as Profile[]);const {data:t}=await supabase.from('teams').select('id,name').eq('is_active',true).order('name');setTeams((t||[]) as Team[]);if(t?.[0]&&!teamId)setTeamId(t[0].id)}setReady(true)}
 useEffect(()=>{load()},[])
 async function setStatus(id:string,status:'approved'|'denied'){const {error}=await supabase.from('profiles').update({status,booking_enabled:status==='approved'}).eq('id',id);setMsg(error?error.message:`Account ${status}.`);if(!error)load()}
 async function addLeague(e:FormEvent){e.preventDefault();setMsg('');const t=teams.find(x=>x.id===teamId);const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('bookings').insert({kind:'league',team_id:teamId,title:`${t?.name||'Team'} – League Round`,start_at:easternStamp(date,hour),end_at:easternStamp(date,hour+duration),created_by:u.user?.id});setMsg(error?error.message:'League reservation added.')}
 async function addBlock(e:FormEvent){e.preventDefault();const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('bookings').insert({kind:'blocked',title:blockTitle||'Unavailable',start_at:easternStamp(blockDate,blockHour),end_at:easternStamp(blockDate,blockHour+blockDuration),created_by:u.user?.id});setMsg(error?error.message:'Blocked time added.')}
 if(!ready)return <p>Loading…</p>
 if(!admin)return <div className="card"><h1>Admin</h1><p>This area is available only to approved administrators.</p></div>
 return <><section className="hero"><div className="eyebrow">Administration</div><h1>Simulator & League Admin</h1><p>Approve accounts, schedule league rounds, and block simulator time.</p></section>{msg&&<p className="message">{msg}</p>}
 <section><div className="section-title"><h2>Account Approvals</h2></div>{requests.length===0?<div className="card">No pending, denied, or suspended accounts.</div>:<div className="card table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Status</th><th>Action</th></tr></thead><tbody>{requests.map(p=><tr key={p.id}><td>{p.full_name||'—'}</td><td>{p.email}</td><td>{p.status}</td><td className="actions"><button className="btn small" onClick={()=>setStatus(p.id,'approved')}>Approve</button><button className="btn danger small" onClick={()=>setStatus(p.id,'denied')}>Deny</button></td></tr>)}</tbody></table></div>}</section>
 <div className="grid admin-grid"><div className="card"><h2>Add League Reservation</h2><p className="muted">These display the team name on the public booking calendar.</p><form onSubmit={addLeague} className="form-grid single"><label className="field">Team<select value={teamId} onChange={e=>setTeamId(e.target.value)}>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="field">Date<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field">Start<select value={hour} onChange={e=>setHour(Number(e.target.value))}>{Array.from({length:14},(_,i)=>i+7).map(h=><option key={h} value={h}>{new Intl.DateTimeFormat('en-US',{hour:'numeric'}).format(new Date(2020,0,1,h))}</option>)}</select></label><label className="field">Length<select value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value={1}>1 hour</option><option value={2}>2 hours</option><option value={3}>3 hours</option></select></label><button className="btn">Add League Reservation</button></form></div>
 <div className="card"><h2>Block Simulator Time</h2><p className="muted">Use for maintenance, events, or other unavailable periods.</p><form onSubmit={addBlock} className="form-grid single"><label className="field">Label<input placeholder="Unavailable" value={blockTitle} onChange={e=>setBlockTitle(e.target.value)}/></label><label className="field">Date<input type="date" required value={blockDate} onChange={e=>setBlockDate(e.target.value)}/></label><label className="field">Start<select value={blockHour} onChange={e=>setBlockHour(Number(e.target.value))}>{Array.from({length:14},(_,i)=>i+7).map(h=><option key={h} value={h}>{new Intl.DateTimeFormat('en-US',{hour:'numeric'}).format(new Date(2020,0,1,h))}</option>)}</select></label><label className="field">Length<select value={blockDuration} onChange={e=>setBlockDuration(Number(e.target.value))}><option value={1}>1 hour</option><option value={2}>2 hours</option><option value={3}>3 hours</option></select></label><button className="btn">Block Time</button></form></div></div>
 </>
}
