'use client'
import { useEffect,useMemo,useState } from 'react'
import { supabase } from '@/lib/supabase'

type Team={id:string;name:string}
type Month={id:string;month_start:string;course_name:string;bonus_birdie_value:number}
type Score={id?:string;league_month_id:string;team_id:string;week_number:number;raw_stableford:number;bonus_birdies:number;bonus_points:number;handicap_points:number;official_total:number|null;status:string}
type Handicap={team_id:string;handicap_points:number}
export default function WeeklyScoring({seasonId,teams}:{seasonId:string;teams:Team[]}){
 const [months,setMonths]=useState<Month[]>([]),[monthId,setMonthId]=useState(''),[week,setWeek]=useState(1),[scores,setScores]=useState<Score[]>([]),[handicaps,setHandicaps]=useState<Handicap[]>([]),[draft,setDraft]=useState<Record<string,{raw:string;birdies:string}>>({}),[msg,setMsg]=useState('')
 async function loadMonths(){if(!seasonId)return;const {data}=await supabase.from('league_months').select('id,month_start,course_name,bonus_birdie_value').eq('season_id',seasonId).order('month_start');setMonths((data||[]) as Month[]);if(data?.length&&!monthId)setMonthId(data[0].id)}
 async function loadScores(){if(!monthId)return;const [{data:s},{data:h}]=await Promise.all([supabase.from('weekly_scores').select('*').eq('league_month_id',monthId),supabase.from('monthly_team_handicaps').select('team_id,handicap_points').eq('league_month_id',monthId)]);setScores((s||[]) as Score[]);setHandicaps((h||[]) as Handicap[]);const d:Record<string,{raw:string;birdies:string}>={};teams.forEach(t=>{const x=(s||[]).find((z:any)=>z.team_id===t.id&&z.week_number===week);d[t.id]={raw:x?String(x.raw_stableford):'',birdies:x?String(x.bonus_birdies):''}});setDraft(d)}
 useEffect(()=>{loadMonths()},[seasonId]);useEffect(()=>{loadScores()},[monthId,week,teams.length])
 const month=months.find(m=>m.id===monthId);const hv=(id:string)=>Number(handicaps.find(h=>h.team_id===id)?.handicap_points||0)
 async function save(team:Team){if(!month)return;const d=draft[team.id]||{raw:'',birdies:''};if(d.raw==='')return setMsg('Enter a raw Stableford score first.');const raw=Number(d.raw),birdies=Number(d.birdies||0),bonus=birdies*Number(month.bonus_birdie_value),handicap=hv(team.id),total=raw+bonus+handicap;const payload={league_month_id:monthId,team_id:team.id,week_number:week,raw_stableford:raw,bonus_birdies:birdies,bonus_points:bonus,handicap_points:handicap,status:'approved'};const {error}=await supabase.from('weekly_scores').upsert(payload,{onConflict:'league_month_id,team_id,week_number'});setMsg(error?error.message:`${team.name} Week ${week} saved — ${total.toFixed(1)} points.`);if(!error)loadScores()}
 const standings=useMemo(()=>teams.map(t=>{const ss=scores.filter(s=>s.team_id===t.id&&s.week_number<=3);return {team:t,total:ss.reduce((a,s)=>a+Number(s.official_total||0),0),played:ss.length}}).sort((a,b)=>b.total-a.total),[scores,teams])
 return <section><div className="section-title"><div><h2>Weekly Scoring & Standings</h2><p className="muted">Enter raw Stableford and bonus birdies. Bonus points and the saved monthly handicap are calculated automatically.</p></div></div>{msg&&<p className="message">{msg}</p>}<div className="card"><div className="form-grid"><label className="field">Month<select value={monthId} onChange={e=>setMonthId(e.target.value)}>{months.map(m=><option key={m.id} value={m.id}>{new Date(m.month_start+'T12:00:00').toLocaleDateString('en-US',{month:'long'})} — {m.course_name}</option>)}</select></label><label className="field">Week<select value={week} onChange={e=>setWeek(Number(e.target.value))}>{[1,2,3,4].map(w=><option key={w} value={w}>Week {w}</option>)}</select></label></div>{!month?<p className="muted">Save a Monthly League Setup first.</p>:<div className="table-wrap"><table><thead><tr><th>Team</th><th>Raw Stableford</th><th>Bonus Birdies</th><th>Bonus</th><th>Handicap</th><th>Official Total</th><th></th></tr></thead><tbody>{teams.map(t=>{const d=draft[t.id]||{raw:'',birdies:''};const bonus=Number(d.birdies||0)*Number(month.bonus_birdie_value),total=d.raw===''?null:Number(d.raw)+bonus+hv(t.id);return <tr key={t.id}><td><strong>{t.name}</strong></td><td><input type="number" step="0.1" value={d.raw} onChange={e=>setDraft(v=>({...v,[t.id]:{...d,raw:e.target.value}}))}/></td><td><input type="number" min="0" value={d.birdies} onChange={e=>setDraft(v=>({...v,[t.id]:{...d,birdies:e.target.value}}))}/></td><td>{bonus.toFixed(1)}</td><td>{hv(t.id).toFixed(1)}</td><td><strong>{total===null?'—':total.toFixed(1)}</strong></td><td><button className="btn small" onClick={()=>save(t)}>Save</button></td></tr>})}</tbody></table></div>}</div>{month&&<div className="card"><h3>Weeks 1–3 Seeding Preview</h3><div className="table-wrap"><table><thead><tr><th>#</th><th>Team</th><th>Rounds</th><th>Adjusted Total</th></tr></thead><tbody>{standings.map((r,i)=><tr key={r.team.id}><td className="rank">{i+1}</td><td>{r.team.name}</td><td>{r.played}</td><td><strong>{r.total.toFixed(1)}</strong></td></tr>)}</tbody></table></div></div>}</section>
}
