'use client'
import {useEffect,useMemo,useState} from 'react'
import {useParams} from 'next/navigation'
import {PlayerPage} from '@/components/PlayerMobileChrome'
import {supabase} from '@/lib/supabase'

export default function RoundCard(){
 const {id}=useParams<{id:string}>(),[r,setR]=useState<any>(null),[players,setPlayers]=useState<any[]>([]),[img,setImg]=useState('')
 useEffect(()=>{(async()=>{const {data:x}=await supabase.from('round_score_submissions').select('*,teams(name),league_months(month_start,course_name,bonus_hole_1,bonus_hole_2)').eq('id',id).single();setR(x);if(x){const {data:p}=await supabase.from('players').select('full_name').eq('team_id',x.team_id).eq('is_active',true).order('full_name');setPlayers(p||[]);if(x.image_path){const {data:s}=await supabase.storage.from('round-scorecards').createSignedUrl(x.image_path,600);setImg(s?.signedUrl||'')}}})()},[id])
 const holes=useMemo(()=>{if(!r)return[];const extras=[Number(r.league_months?.bonus_hole_1),Number(r.league_months?.bonus_hole_2)].filter(h=>h>=1&&h<=18);return Array.from(new Set([...Array.from({length:10},(_,i)=>i+1),...extras]))},[r])
 if(!r)return <PlayerPage title="Round Scorecard"><div className="simple-mobile-page"><p>Loading scorecard…</p></div></PlayerPage>
 const scores=r.hole_scores||[],pars=r.hole_pars||[],points=r.stableford_points||[],month=new Date(r.league_months.month_start+'T12:00:00').toLocaleString('en-US',{month:'long',year:'numeric'})
 return <PlayerPage title="Round Scorecard"><div className="digital-scorecard"><div className="round-card-hero"><div><h1>{r.teams?.name}</h1><h2>{month} · Week {r.week_number} Round</h2><p>{r.league_months?.course_name}</p></div><span className="round-complete">✓ ROUND COMPLETE</span></div><div className="scorecard-scroll"><table className="digital-score-table"><thead><tr><th>HOLE</th>{holes.map(h=><th key={h}>{h}{h>10?' ★':''}</th>)}<th>TOTAL</th></tr></thead><tbody><tr><th>PAR</th>{holes.map(h=><td key={h}>{pars[h-1]||'—'}</td>)}<td>—</td></tr>{players.map((p,i)=><tr key={i}><th>{p.full_name}</th>{holes.map(h=><td key={h}>{scores[h-1]||'—'}</td>)}<td>{scores.slice(0,10).reduce((a:number,b:any)=>a+Number(b||0),0)}</td></tr>)}<tr className="stableford-row"><th>STABLEFORD PTS</th>{holes.map(h=><td key={h}>{h<=10?(points[h-1]??0):'Bonus'}</td>)}<td>{r.raw_stableford}</td></tr></tbody></table></div><div className="stableford-key"><b>Stableford:</b> 5 Albatross · 4 Eagle · 3 Birdie · 2 Par · 1 Bogey · 0 Double+</div><div className="round-summary"><div><span>Raw Stableford</span><b>{r.raw_stableford}</b></div><div><span>Bonus Points</span><b>+{Number(r.bonus_points).toFixed(1)}</b></div><div><span>Monthly Handicap</span><b>{Number(r.handicap_points)>=0?'+':''}{Number(r.handicap_points).toFixed(1)}</b></div><div className="official-score"><span>Official Round Score</span><b>{Number(r.official_total).toFixed(1)}</b></div></div>{img&&<details className="original-scorecard"><summary>View Original GSPro Scorecard</summary><img src={img} alt="Original GSPro scorecard"/></details>}</div></PlayerPage>
}
