'use client'
import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react'
import {supabase} from '@/lib/supabase'
import {PlayerPage} from '@/components/PlayerMobileChrome'
type Post={id:string;user_id:string;audience:'league'|'team';team_id:string|null;body:string;parent_id:string|null;created_at:string;profiles?:{full_name:string;avatar_url:string|null}|null}
type Reaction={post_id:string;user_id:string;reaction:'like'|'love'|'clap'|'golf'}
const icons={like:'👍',love:'❤️',clap:'👏',golf:'⛳'} as const
export default function LeagueChat(){
 const [userId,setUserId]=useState(''),[teamId,setTeamId]=useState<string|null>(null),[posts,setPosts]=useState<Post[]>([]),[reactions,setReactions]=useState<Reaction[]>([]),[body,setBody]=useState(''),[audience,setAudience]=useState<'league'|'team'>('league'),[replyTo,setReplyTo]=useState<Post|null>(null),[msg,setMsg]=useState(''),[saving,setSaving]=useState(false)
 const load=useCallback(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;setUserId(user.id);const {data:pr}=await supabase.from('profiles').select('player_id').eq('id',user.id).single();let tid:string|null=null;if(pr?.player_id){const {data:pl}=await supabase.from('players').select('team_id').eq('id',pr.player_id).single();tid=pl?.team_id||null}setTeamId(tid);const {data:p}=await supabase.from('chat_posts').select('id,user_id,audience,team_id,body,parent_id,created_at,profiles!chat_posts_user_id_fkey(full_name,avatar_url)').order('created_at',{ascending:false}).limit(150);const {data:r}=await supabase.from('chat_reactions').select('post_id,user_id,reaction');setPosts((p||[]) as unknown as Post[]);setReactions((r||[]) as Reaction[])},[])
 useEffect(()=>{load();setTimeout(()=>{const id=new URLSearchParams(window.location.search).get('post');if(id)document.getElementById('chat-'+id)?.scrollIntoView({behavior:'smooth',block:'center'})},500);(async()=>{const {data:{user}}=await supabase.auth.getUser();if(user){await supabase.from('chat_read_state').upsert({user_id:user.id,last_seen_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'user_id'});window.dispatchEvent(new Event('chat-unread-changed'))}})();const ch=supabase.channel('league-chat-live').on('postgres_changes',{event:'*',schema:'public',table:'chat_posts'},load).on('postgres_changes',{event:'*',schema:'public',table:'chat_reactions'},load).subscribe();return()=>{supabase.removeChannel(ch)}},[load])
 const roots=useMemo(()=>posts.filter(p=>!p.parent_id),[posts])
 async function submit(e:FormEvent){e.preventDefault();const text=body.trim();if(!text)return;setSaving(true);setMsg('');let postAudience=audience;let postTeamId=audience==='team'?teamId:null;let parentId:string|null=null;if(replyTo){const {data:parent,error:parentError}=await supabase.from('chat_posts').select('id,audience,team_id').eq('id',replyTo.id).maybeSingle();if(parentError||!parent){setReplyTo(null);setMsg('That message is no longer available. The chat has been refreshed.');await load();setSaving(false);return}parentId=parent.id;postAudience=parent.audience as 'league'|'team';postTeamId=parent.team_id||null}else if(audience==='team'&&!teamId){setMsg('Your account must be linked to a team to post to My Team.');setSaving(false);return}const {data:created,error}=await supabase.from('chat_posts').insert({user_id:userId,audience:postAudience,team_id:postTeamId,body:text,parent_id:parentId}).select('id').single();if(error){if(error.message.includes('chat_posts_parent_id_fkey')){setReplyTo(null);setMsg('That message was removed before your reply could be posted. Please try again.');await load()}else setMsg(error.message)}else{const {data:{session}}=await supabase.auth.getSession();if(session&&created?.id)fetch('/api/push/chat',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({postId:created.id})}).catch(()=>{});setBody('');setReplyTo(null);await load()}setSaving(false)}
 async function react(postId:string,reaction:Reaction['reaction']){const existing=reactions.find(r=>r.post_id===postId&&r.user_id===userId&&r.reaction===reaction);if(existing)await supabase.from('chat_reactions').delete().eq('post_id',postId).eq('user_id',userId).eq('reaction',reaction);else await supabase.from('chat_reactions').insert({post_id:postId,user_id:userId,reaction});load()}
 async function remove(p:Post){if(!confirm('Delete this chat message?'))return;const {error}=await supabase.from('chat_posts').delete().eq('id',p.id);if(error)setMsg(error.message);else load()}
 function card(p:Post,isReply=false){const rs=reactions.filter(r=>r.post_id===p.id);return <article id={'chat-'+p.id} key={p.id} className={'chat-card '+(isReply?'chat-reply':'')}><div className="chat-author">{p.profiles?.avatar_url?<img src={p.profiles.avatar_url} alt=""/>:<span>👤</span>}<div><strong>{p.profiles?.full_name||'League Player'}</strong><small>{p.audience==='team'?'My Team':'Entire League'} · {new Date(p.created_at).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small></div></div><p>{p.body}</p><div className="chat-actions">{(Object.keys(icons) as Reaction['reaction'][]).map(k=>{const count=rs.filter(r=>r.reaction===k).length;const mine=rs.some(r=>r.reaction===k&&r.user_id===userId);return <button type="button" key={k} className={mine?'active':''} onClick={()=>react(p.id,k)}>{icons[k]}{count>0&&<b>{count}</b>}</button>})}<button type="button" onClick={()=>{setReplyTo(p);setAudience(p.audience);setTimeout(()=>document.getElementById('chat-compose')?.focus(),0)}}>Reply</button>{p.user_id===userId&&<button type="button" onClick={()=>remove(p)}>Delete</button>}</div></article>}
 return <PlayerPage title="League Chat"><div className="simple-mobile-page chat-page"><h1>League Chat</h1><p className="muted">Ask questions, congratulate a great round, or chat with the entire league or just your team.</p>{msg&&<p className="message">{msg}</p>}<form className="card chat-compose" onSubmit={submit}><div className="chat-compose-top"><strong>{replyTo?`Reply to ${replyTo.profiles?.full_name||'player'}`:'New Message'}</strong>{replyTo&&<button type="button" onClick={()=>setReplyTo(null)}>Cancel Reply</button>}</div><select value={audience} onChange={e=>setAudience(e.target.value as 'league'|'team')}><option value="league">Entire League</option><option value="team" disabled={!teamId}>My Team{!teamId?' (account not linked)':''}</option></select><textarea id="chat-compose" maxLength={1000} rows={3} placeholder="Write a message…" value={body} onChange={e=>setBody(e.target.value)}/><button className="btn" disabled={saving||!body.trim()}>{saving?'Posting…':replyTo?'Post Reply':'Post Message'}</button></form><div className="chat-feed">{roots.length?roots.map(p=><section key={p.id}>{card(p)}{posts.filter(x=>x.parent_id===p.id).sort((a,b)=>a.created_at.localeCompare(b.created_at)).map(x=>card(x,true))}</section>):<div className="card">No chat messages yet. Start the conversation!</div>}</div></div></PlayerPage>
}
