'use client'
import Link from 'next/link'
import {useCallback,useEffect,useRef,useState} from 'react'
import type {ComponentType, SVGProps} from 'react'
import {supabase} from '@/lib/supabase'
import {ReserveIcon,CalendarIcon,StandingsIcon,TrophyIcon,MatchPlayIcon,MessagesIcon,ChatIcon,FlagIcon,TeamsIcon,RulesIcon,HomeIcon} from '@/components/PlayerIcons'

type MenuItem={href:string;Icon:ComponentType<SVGProps<SVGSVGElement>>;title:string;desc:string}
const items:MenuItem[]=[
 {href:'/book',Icon:ReserveIcon,title:'Reserve Sim',desc:'Check availability and reserve simulator time'},
 {href:'/my-bookings',Icon:CalendarIcon,title:'My Sim Reservations',desc:'View and manage your simulator reservations'},
 {href:'/standings',Icon:StandingsIcon,title:'Monthly Standings',desc:'View monthly standings and team rankings'},
 {href:'/cup',Icon:TrophyIcon,title:'Cup Standings',desc:'View Cup Points and monthly totals'},
 {href:'/cup#match-play',Icon:MatchPlayIcon,title:'Match Play',desc:'View your Week 4 matchups and results'},
 {href:'/messages',Icon:MessagesIcon,title:'Messages',desc:'Read league messages and announcements'},
 {href:'/chat',Icon:ChatIcon,title:'League Chat',desc:'Chat with the entire league or just your team'},
 {href:'/results',Icon:FlagIcon,title:'Results',desc:'View past results and round history'},
 {href:'/teams',Icon:TeamsIcon,title:'Teams',desc:'View league teams and players'},
 {href:'/rules',Icon:RulesIcon,title:'Rules',desc:'View league rules and point system'}
]
export default function Home(){
 const [profile,setProfile]=useState<any>(null),[open,setOpen]=useState(false),[unread,setUnread]=useState(0),[chatUnread,setChatUnread]=useState(0),[snapshot,setSnapshot]=useState<any>(null); const wrap=useRef<HTMLDivElement>(null)
 const loadPlayer=useCallback(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setProfile(null);setUnread(0);setChatUnread(0);return}; const [{data:p},{data:a},{data:r}]=await Promise.all([supabase.from('profiles').select('full_name,avatar_url,player_id').eq('id',user.id).single(),supabase.from('announcements').select('id').or(`expires_at.is.null,expires_at.gt.${new Date().toISOString()}`),supabase.from('announcement_reads').select('announcement_id').eq('user_id',user.id)]);setProfile(p); const read=new Set((r||[]).map(x=>x.announcement_id));setUnread((a||[]).filter(x=>!read.has(x.id)).length); const {data:state}=await supabase.from('chat_read_state').select('last_seen_at').eq('user_id',user.id).maybeSingle(); const since=state?.last_seen_at||'1970-01-01T00:00:00Z'; const {data:chat}=await supabase.from('chat_posts').select('id,user_id').gt('created_at',since).neq('user_id',user.id); setChatUnread((chat||[]).length);
 if(p?.player_id){
  const {data:player}=await supabase.from('players').select('id,team_id,season_id').eq('id',p.player_id).maybeSingle();
  if(player?.team_id&&player?.season_id){
   const [{data:team},{data:months},{data:teams}]=await Promise.all([supabase.from('teams').select('id,name').eq('id',player.team_id).maybeSingle(),supabase.from('league_months').select('id,month_start,course_name').eq('season_id',player.season_id).order('month_start'),supabase.from('teams').select('id,name').eq('season_id',player.season_id).eq('is_active',true)]);
   const ms=months||[]; let month:any=null; if(ms.length){const today=new Date();today.setHours(0,0,0,0);month=ms.find((m:any)=>new Date(m.month_start+'T12:00:00')>=today)||ms[ms.length-1]}
   const monthIds=ms.map((m:any)=>m.id);
   const [{data:scores},{data:cup},{data:matches}]=await Promise.all([monthIds.length?supabase.from('weekly_scores').select('league_month_id,team_id,week_number,official_total,status').in('league_month_id',monthIds).eq('status','approved'):Promise.resolve({data:[]}),monthIds.length?supabase.from('cup_points').select('league_month_id,team_id,points').in('league_month_id',monthIds):Promise.resolve({data:[]}),month?supabase.from('week4_matchups').select('team_high_id,team_low_id').eq('league_month_id',month.id):Promise.resolve({data:[]})]);
   const allScores:any[]=scores||[], activeTeams:any[]=teams||[]; const monthScores=month?allScores.filter(x=>x.league_month_id===month.id&&x.week_number<=3):[]; const mine=month?allScores.filter(x=>x.league_month_id===month.id&&x.team_id===player.team_id).sort((a,b)=>a.week_number-b.week_number):[]; const monthlyTotals=activeTeams.map(t=>({id:t.id,total:monthScores.filter(x=>x.team_id===t.id).reduce((a,x)=>a+Number(x.official_total||0),0),played:monthScores.some(x=>x.team_id===t.id)})).sort((a,b)=>b.total-a.total); const myMonthly=monthlyTotals.find(x=>x.id===player.team_id); const monthlyRank=myMonthly?.played?monthlyTotals.findIndex(x=>x.id===player.team_id)+1:null;
   const cupTotals=activeTeams.map(t=>({id:t.id,total:(cup||[]).filter((x:any)=>x.team_id===t.id).reduce((a:number,x:any)=>a+Number(x.points||0),0)})).sort((a,b)=>b.total-a.total); const myCup=cupTotals.find(x=>x.id===player.team_id); const cupRank=myCup&&myCup.total>0?cupTotals.findIndex(x=>x.id===player.team_id)+1:null; const nextWeek=Math.min(4,(mine.length?Math.max(...mine.map(x=>Number(x.week_number)))+1:1)); const match=(matches||[]).find((m:any)=>m.team_high_id===player.team_id||m.team_low_id===player.team_id); const opponentId=match?(match.team_high_id===player.team_id?match.team_low_id:match.team_high_id):null; const opponent=activeTeams.find(t=>t.id===opponentId)?.name||null;
   setSnapshot({team:team?.name||'My Team',course:month?.course_name||'Not set',month:month?new Date(month.month_start+'T12:00:00').toLocaleDateString('en-US',{month:'long'}):'',week:nextWeek,monthlyRank,cupRank,cupPoints:myCup?.total||0,opponent});
  }
 }
},[])
 useEffect(()=>{loadPlayer(); const refresh=()=>loadPlayer(); const visible=()=>{if(document.visibilityState==='visible')loadPlayer()}; const timer=window.setInterval(loadPlayer,15000); window.addEventListener('focus',refresh); window.addEventListener('league-unread-changed',refresh); window.addEventListener('chat-unread-changed',refresh); document.addEventListener('visibilitychange',visible); const channel=supabase.channel('home-announcements-live').on('postgres_changes',{event:'*',schema:'public',table:'announcements'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'announcement_reads'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'chat_posts'},refresh).subscribe(); return()=>{window.clearInterval(timer);window.removeEventListener('focus',refresh);window.removeEventListener('league-unread-changed',refresh);window.removeEventListener('chat-unread-changed',refresh);document.removeEventListener('visibilitychange',visible);supabase.removeChannel(channel)}},[loadPlayer])
 useEffect(()=>{const fn=(e:MouseEvent)=>{if(wrap.current&&!wrap.current.contains(e.target as Node))setOpen(false)};document.addEventListener('mousedown',fn);return()=>document.removeEventListener('mousedown',fn)},[])
 async function logout(){await supabase.auth.signOut();location.href='/login'}
 return <div className="mobile-home">
  <section className="mobile-brand"><img src="/logo-golf-league.png" alt="Tom Krise 19th Hole Golf League"/><div className="profile-wrap" ref={wrap}><button className="profile-button" onClick={()=>setOpen(!open)} aria-label="Open profile menu">{profile?.avatar_url?<img src={profile.avatar_url} alt="Profile"/>:<span>👤</span>}<b>⌄</b></button>{open&&<div className="profile-menu"><Link href="/profile">My Profile</Link><Link href="/settings">Settings</Link><button onClick={logout}>Log Out ↪</button></div>}</div></section>
  {snapshot&&<section className="home-snapshot" aria-label="Current league snapshot"><div className="home-snapshot-head"><div><small>CURRENT LEAGUE SNAPSHOT</small><strong>{snapshot.team}</strong></div><Link href="/my-team">My Team ›</Link></div><div className="home-snapshot-grid"><Link href="/my-team" className="home-snapshot-cell"><small>Course</small><strong>{snapshot.course}</strong><span>{snapshot.month}{snapshot.month?` • Week ${snapshot.week}`:`Week ${snapshot.week}`}</span></Link><Link href="/standings" className="home-snapshot-cell"><small>Monthly</small><strong>{snapshot.monthlyRank?`#${snapshot.monthlyRank}`:'—'}</strong><span>Position</span></Link><Link href="/cup" className="home-snapshot-cell"><small>Cup</small><strong>{snapshot.cupRank?`#${snapshot.cupRank}`:'—'}</strong><span>{snapshot.cupPoints} pts</span></Link>{snapshot.opponent&&<Link href="/cup#match-play" className="home-snapshot-cell"><small>Match Play</small><strong>vs {snapshot.opponent}</strong><span>Week 4</span></Link>}</div></section>}
  <nav className="mobile-menu">{items.map(({href,Icon,title,desc})=><Link href={href} className="mobile-menu-row" key={title}><span className="menu-icon"><Icon /></span><span className="menu-copy"><strong>{title}</strong><small>{desc}</small></span>{title==='Messages'&&unread>0&&<span className="unread-badge">{unread}</span>}{title==='League Chat'&&chatUnread>0&&<span className="unread-badge">{chatUnread}</span>}<span className="menu-arrow">›</span></Link>)}</nav>
  <Bottom unread={unread}/>
 </div>
}
function Bottom({unread}:{unread:number}){return <nav className="mobile-bottom"><Link className="active" href="/"><span><HomeIcon /></span><b>Home</b></Link><Link href="/my-bookings"><span><CalendarIcon /></span><b>Reservations</b></Link><Link href="/my-team"><span><TeamsIcon /></span><b>My Team</b></Link><Link href="/messages" className="bottom-message"><span><MessagesIcon /></span>{unread>0&&<i>{unread}</i>}<b>Messages</b></Link></nav>}
