import {NextRequest,NextResponse} from 'next/server'
import {createClient} from '@supabase/supabase-js'

function clients(token:string){const url=process.env.NEXT_PUBLIC_SUPABASE_URL!,pub=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,secret=process.env.SUPABASE_SECRET_KEY!;return {auth:createClient(url,pub,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}}),admin:createClient(url,secret,{auth:{persistSession:false}})}}

async function syncOpenMeetingRoster(admin:any,meeting:{id:string,season_id:string,is_open:boolean}){if(!meeting.is_open)return;const [{data:players},{data:existing}]=await Promise.all([admin.from('players').select('id,team_id,full_name,teams!inner(name,is_active)').eq('season_id',meeting.season_id).eq('is_active',true).eq('teams.is_active',true),admin.from('league_meeting_invitees').select('player_id').eq('meeting_id',meeting.id)]);const have=new Set((existing||[]).map((x:any)=>x.player_id).filter(Boolean));const rows=(players||[]).filter((p:any)=>!have.has(p.id)).map((p:any)=>({meeting_id:meeting.id,player_id:p.id,team_id:p.team_id,player_name:p.full_name,team_name:p.teams?.name||'Team'}));if(rows.length)await admin.from('league_meeting_invitees').insert(rows)}
async function authorize(req:NextRequest){const token=(req.headers.get('authorization')||'').replace(/^Bearer /,'');if(!token)return null;const {auth,admin}=clients(token);const {data:{user}}=await auth.auth.getUser(token);if(!user)return null;const {data:p}=await admin.from('profiles').select('role,status').eq('id',user.id).maybeSingle();if(!p||p.role!=='admin'||p.status!=='approved')return null;return {admin,user}}
export async function GET(req:NextRequest){const access=await authorize(req);if(!access)return NextResponse.json({error:'Admin access required.'},{status:403});const {admin}=access;const {data:openMeetings}=await admin.from('league_meetings').select('id,season_id,is_open').eq('is_open',true);for(const meeting of openMeetings||[])await syncOpenMeetingRoster(admin,meeting);const {data,error}=await admin.from('league_meetings').select('id,title,meeting_at,location,message,public_token,is_open,created_at,league_meeting_invitees(id,player_name,team_name,is_coming,response_status,responded_at)').order('meeting_at',{ascending:false});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({meetings:data||[]})}
export async function POST(req:NextRequest){const access=await authorize(req);if(!access)return NextResponse.json({error:'Admin access required.'},{status:403});const {admin,user}=access;const body=await req.json();const title=String(body.title||'League Meeting').trim(),meetingAt=String(body.meetingAt||''),location=String(body.location||'').trim(),message=String(body.message||'').trim();if(!meetingAt)return NextResponse.json({error:'Meeting date and time are required.'},{status:400});const {data:season}=await admin.from('seasons').select('id').eq('is_active',true).eq('is_closed',false).limit(1).maybeSingle();if(!season)return NextResponse.json({error:'No active season found.'},{status:400});const {data:meeting,error}=await admin.from('league_meetings').insert({season_id:season.id,title,meeting_at:meetingAt,location:location||null,message:message||null,created_by:user.id}).select('*').single();if(error)return NextResponse.json({error:error.message},{status:400});const {data:players,error:pErr}=await admin.from('players').select('id,team_id,full_name,teams!inner(name,is_active)').eq('season_id',season.id).eq('is_active',true).eq('teams.is_active',true).order('full_name');if(pErr){await admin.from('league_meetings').delete().eq('id',meeting.id);return NextResponse.json({error:pErr.message},{status:400})}const rows=(players||[]).map((p:any)=>({meeting_id:meeting.id,player_id:p.id,team_id:p.team_id,player_name:p.full_name,team_name:p.teams?.name||'Team'}));if(rows.length){const {error:iErr}=await admin.from('league_meeting_invitees').insert(rows);if(iErr){await admin.from('league_meetings').delete().eq('id',meeting.id);return NextResponse.json({error:iErr.message},{status:400})}}return NextResponse.json({ok:true,meeting,inviteeCount:rows.length})}
export async function PATCH(req:NextRequest){const access=await authorize(req);if(!access)return NextResponse.json({error:'Admin access required.'},{status:403});const {admin}=access;const body=await req.json();if(!body.id)return NextResponse.json({error:'Meeting ID required.'},{status:400});const patch:any={updated_at:new Date().toISOString()};for(const k of ['title','location','message','is_open'])if(body[k]!==undefined)patch[k]=body[k];if(body.meetingAt)patch.meeting_at=body.meetingAt;const {error}=await admin.from('league_meetings').update(patch).eq('id',body.id);if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true})}
