'use client'
import {useEffect,useState} from 'react';import {supabase} from '@/lib/supabase'; import {PlayerPage} from '@/components/PlayerMobileChrome'
const VAPID_PUBLIC_KEY='BNfpFrTXfBnim6gbXvWm8XknDPLqY16Wo0eKalryPEcUKZ5M6v-8J6JdLyp_vaPzEhaxxfGp1vwJZNgxtdiQtMM'
function keyBytes(s:string){const pad='='.repeat((4-s.length%4)%4),b64=(s+pad).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(b64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
export default function Settings(){const [pw,setPw]=useState(''),[msg,setMsg]=useState(''),[pushMsg,setPushMsg]=useState(''),[pushOn,setPushOn]=useState(false),[busy,setBusy]=useState(false),[chatPush,setChatPush]=useState(true)
useEffect(()=>{(async()=>{if(!('serviceWorker'in navigator)||!('PushManager'in window))return;const reg=await navigator.serviceWorker.register('/sw.js');const sub=await reg.pushManager.getSubscription();setPushOn(!!sub);const {data:{user}}=await supabase.auth.getUser();if(user){const {data:p}=await supabase.from('chat_notification_preferences').select('enabled').eq('user_id',user.id).maybeSingle();setChatPush(p?.enabled!==false)}})()},[])
async function save(){if(pw.length<6){setMsg('Password must be at least 6 characters.');return}const {error}=await supabase.auth.updateUser({password:pw});setMsg(error?error.message:'Password updated.');if(!error)setPw('')}
async function enablePush(){setBusy(true);setPushMsg('');try{if(!('serviceWorker'in navigator)||!('PushManager'in window))throw new Error('Push notifications are not supported on this device/browser.');const standalone=window.matchMedia('(display-mode: standalone)').matches||(navigator as any).standalone===true;const isiOS=/iPad|iPhone|iPod/.test(navigator.userAgent);if(isiOS&&!standalone)throw new Error('On iPhone, first add the golf league app to your Home Screen, then open the app and enable notifications here.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Notification permission was not allowed. You can enable it later in your phone settings.');const reg=await navigator.serviceWorker.register('/sw.js');await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyBytes(VAPID_PUBLIC_KEY)});const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Please sign in again.');const j=sub.toJSON();const {error}=await supabase.from('push_subscriptions').upsert({user_id:user.id,endpoint:sub.endpoint,p256dh:j.keys?.p256dh||null,auth:j.keys?.auth||null,updated_at:new Date().toISOString()},{onConflict:'endpoint'});if(error)throw error;setPushOn(true);setPushMsg('Phone notifications are enabled for this device.')}catch(e:any){setPushMsg(e.message||'Unable to enable notifications.')}finally{setBusy(false)}}

async function toggleChatPush(){const next=!chatPush;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {error}=await supabase.from('chat_notification_preferences').upsert({user_id:user.id,enabled:next,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)setPushMsg(error.message);else setChatPush(next)}
async function disablePush(){setBusy(true);setPushMsg('');try{const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.getSubscription();if(sub){await supabase.from('push_subscriptions').delete().eq('endpoint',sub.endpoint);await sub.unsubscribe()}setPushOn(false);setPushMsg('Phone notifications are turned off for this device.')}catch(e:any){setPushMsg(e.message||'Unable to turn off notifications.')}finally{setBusy(false)}}
return <PlayerPage title="Settings"><div className="simple-mobile-page"><h1>Settings</h1><div className="card notification-settings"><h2>Phone Notifications</h2><p className="muted">Get league announcements plus simulator reservation reminders 24 hours and 1 hour before your reserved time.</p><div className="notification-status"><span className={'status-dot '+(pushOn?'on':'')}></span><strong>{pushOn?'Notifications Enabled':'Notifications Off'}</strong></div><button className="btn" disabled={busy} onClick={pushOn?disablePush:enablePush}>{busy?'Please wait…':pushOn?'Turn Off Notifications':'Enable Notifications'}</button>{pushMsg&&<p className="message">{pushMsg}</p>}<hr/><h3>League Chat Notifications</h3><p className="muted">Get phone alerts for new League Chat posts and replies. Reactions do not send notifications.</p><div className="notification-status"><span className={'status-dot '+(chatPush?'on':'')}></span><strong>{chatPush?'Chat Enabled':'Chat Notifications Off'}</strong></div><button className="btn" onClick={toggleChatPush}>{chatPush?'Turn Off League Chat Alerts':'Turn On League Chat Alerts'}</button></div><div className="card"><h2>Account</h2><label>New Password<input type="password" value={pw} onChange={e=>setPw(e.target.value)} placeholder="Enter a new password"/></label><button className="btn" onClick={save}>Update Password</button>{msg&&<p>{msg}</p>}</div></div></PlayerPage>}
