'use client'
import {useEffect,useState} from 'react'
import {supabase} from '@/lib/supabase'
import {AdminDenied,AdminFrame,useAdminGuard} from '../admin-shared'
type Profile={id:string;full_name:string;email:string|null;status:string;booking_enabled:boolean;created_at:string;player_id:string|null}
type Team={id:string;name:string}
type Player={id:string;team_id:string|null;full_name:string}
export default function Accounts(){const guard=useAdminGuard();const [requests,setRequests]=useState<Profile[]>([]),[approved,setApproved]=useState<Profile[]>([]),[teams,setTeams]=useState<Team[]>([]),[players,setPlayers]=useState<Player[]>([]),[msg,setMsg]=useState('')
 async function load(){if(!guard.admin)return;const [{data:r},{data:a},{data:s}]=await Promise.all([supabase.from('profiles').select('id,full_name,email,status,booking_enabled,created_at,player_id').in('status',['pending','denied','suspended']).order('created_at'),supabase.from('profiles').select('id,full_name,email,status,booking_enabled,created_at,player_id').eq('status','approved').neq('role','admin').order('full_name'),supabase.from('seasons').select('id').eq('is_active',true).eq('is_closed',false).limit(1).maybeSingle()]);setRequests((r||[]) as Profile[]);setApproved((a||[]) as Profile[]);const {data:t}=s?.id?await supabase.from('teams').select('id,name').eq('season_id',s.id).eq('is_active',true).order('name'):await supabase.from('teams').select('id,name').eq('is_active',true).order('name');setTeams((t||[]) as Team[]);const ids=(t||[]).map(x=>x.id);const {data:p}=ids.length?await supabase.from('players').select('id,team_id,full_name').in('team_id',ids).eq('is_active',true).order('full_name'):({data:[]} as any);setPlayers((p||[]) as Player[])}
 useEffect(()=>{load()},[guard.admin])
 async function status(id:string,value:'approved'|'denied'){const {error}=await supabase.from('profiles').update({status:value,booking_enabled:value==='approved'}).eq('id',id);setMsg(error?error.message:`Account ${value}.`);if(!error)load()}
 async function suspend(id:string){const {error}=await supabase.from('profiles').update({status:'suspended',booking_enabled:false}).eq('id',id);setMsg(error?error.message:'Booking access suspended.');if(!error)load()}
 async function link(id:string,playerId:string){const {error}=await supabase.from('profiles').update({player_id:playerId||null}).eq('id',id);setMsg(error?error.message:(playerId?'League player linked.':'League player link removed.'));if(!error)load()}
 const denied=<AdminDenied {...guard}/>;if(denied)return denied;return <AdminFrame title="Accounts" description="Approve players, connect accounts to league rosters, and manage access.">{msg&&<p className="message">{msg}</p>}<section><div className="section-title"><h2>Account Approvals</h2></div>{requests.length===0?<div className="card">No pending, denied, or suspended accounts.</div>:<div className="card table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Status</th><th>Action</th></tr></thead><tbody>{requests.map(p=><tr key={p.id}><td>{p.full_name||'—'}</td><td>{p.email}</td><td>{p.status}</td><td className="actions"><button className="btn small" onClick={()=>status(p.id,'approved')}>Approve</button><button className="btn danger small" onClick={()=>status(p.id,'denied')}>Deny</button></td></tr>)}</tbody></table></div>}</section><section><div className="section-title"><div><h2>Approved Users</h2><p className="muted">Link each account to its league player so team messages reach the correct people.</p></div></div>{approved.length===0?<div className="card">No approved non-admin users yet.</div>:<div className="card table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>League Player / Team</th><th>Booking</th><th>Action</th></tr></thead><tbody>{approved.map(p=><tr key={p.id}><td>{p.full_name||'—'}</td><td>{p.email}</td><td><select className="account-player-select" value={p.player_id||''} onChange={e=>link(p.id,e.target.value)}><option value="">Not linked</option>{teams.map(t=><optgroup key={t.id} label={t.name}>{players.filter(pl=>pl.team_id===t.id).map(pl=><option key={pl.id} value={pl.id}>{pl.full_name}</option>)}</optgroup>)}</select></td><td>{p.booking_enabled?'Enabled':'Disabled'}</td><td><button className="btn danger small" onClick={()=>suspend(p.id)}>Suspend</button></td></tr>)}</tbody></table></div>}</section></AdminFrame>}
