'use client'
import { useEffect,useMemo,useState } from 'react'
import { supabase } from '@/lib/supabase'
type Team={id:string;name:string};type Month={id:string;month_start:string;course_name:string};type Score={team_id:string;week_number:number;official_total:number|null;status:string};type Handicap={team_id:string;handicap_points:number}
export default function TVLeaderboard(){
 const [teams,setTeams]=useState<Team[]>([]),[months,setMonths]=useState<Month[]>([]),[monthId,setMonthId]=useState(''),[scores,setScores]=useState<Score[]>([]),[handicaps,setHandicaps]=useState<Handicap[]>([]),[flash,setFlash]=useState<string|null>(null)
 useEffect(()=>{(async()=>{const {data:s}=await supabase.from('seasons').select('id').eq('is_active',true).eq('is_closed',false).limit(1).maybeSingle();if(!s)return;const [{data:t},{data:m}]=await Promise.all([supabase.from('teams').select('id,name').eq('season_id',s.id).eq('is_active',true),supabase.from('league_months').select('id,month_start,course_name').eq('season_id',s.id).order('month_start')]);setTeams((t||[]) as Team[]);setMonths((m||[]) as Month[]);if(m?.length)setMonthId(m[m.length-1].id)})()},[])
 useEffect(()=>{if(!monthId)return;let alive=true;const load=async()=>{const [{data:a},{data:b}]=await Promise.all([supabase.from('weekly_scores').select('team_id,week_number,official_total,status').eq('league_month_id',monthId).eq('status','approved'),supabase.from('monthly_team_handicaps').select('team_id,handicap_points').eq('league_month_id',monthId)]);if(alive){setScores((a||[]) as Score[]);setHandicaps((b||[]) as Handicap[])}};load();const channel=supabase.channel('tv-'+monthId).on('postgres_changes',{event:'*',schema:'public',table:'weekly_scores',filter:`league_month_id=eq.${monthId}`},p=>{const n=(p.new||p.old) as any;setFlash(n.team_id||null);load();setTimeout(()=>setFlash(null),1800)}).on('postgres_changes',{event:'*',schema:'public',table:'monthly_team_handicaps',filter:`league_month_id=eq.${monthId}`},()=>load()).subscribe();return()=>{alive=false;supabase.removeChannel(channel)}},[monthId])
 const latestWeek=Math.max(1,...scores.filter(s=>s.week_number<=3).map(s=>s.week_number));const calc=(through:number)=>teams.map(t=>({id:t.id,total:scores.filter(s=>s.team_id===t.id&&s.week_number<=through).reduce((a,s)=>a+Number(s.official_total||0),0)})).sort((a,b)=>b.total-a.total)
 const prevRanks=useMemo(()=>{const map=new Map<string,number>();if(latestWeek>1)calc(latestWeek-1).forEach((r,i)=>map.set(r.id,i+1));return map},[teams,scores,latestWeek])
 const rows=useMemo(()=>calc(latestWeek).map((base,i)=>{const t=teams.find(x=>x.id===base.id)!;const wk=(n:number)=>scores.find(s=>s.team_id===t.id&&s.week_number===n)?.official_total;const h=handicaps.find(x=>x.team_id===t.id)?.handicap_points;const old=prevRanks.get(t.id);return{t,rank:i+1,h:h==null?null:Number(h),w1:wk(1),w2:wk(2),w3:wk(3),total:base.total,change:old?old-(i+1):0}}),[teams,scores,handicaps,latestWeek,prevRanks])
 const m=months.find(x=>x.id===monthId),d=m?new Date(m.month_start+'T12:00:00'):null,monthLabel=d?d.toLocaleDateString('en-US',{month:'short'}).toUpperCase()+' '+String(d.getFullYear()).slice(-2):'';const fmt=(v:number|null|undefined)=>v==null?'—':Number(v).toFixed(1)
 return <div className="tv-shell"><div className="tv-top"><div className="tv-brand"><div className="tv-ball">T</div><div><b>TOM KRISE 19TH HOLE GOLF LEAGUE</b><h1>MONTHLY STANDINGS</h1></div></div><div className="tv-meta"><strong>{monthLabel}</strong><span>WEEK {latestWeek} OF 4</span></div></div><div className="tv-table"><div className="tv-row tv-head"><span>RANK</span><span>TEAM</span><span>HANDICAP</span><span>WEEK 1<small>ADJUSTED</small></span><span>WEEK 2<small>ADJUSTED</small></span><span>WEEK 3<small>ADJUSTED</small></span><span>TOTAL<small>ADJUSTED</small></span></div>{rows.map(r=><div className={'tv-row '+(flash===r.t.id?'tv-flash':'')} key={r.t.id}><span className="tv-rank">{r.rank}</span><span className="tv-team">{r.t.name}</span><span className="tv-green">{r.h==null?'—':`${Math.round(r.h)>=0?'+':''}${Math.round(r.h)}`}</span><span>{fmt(r.w1)}</span><span>{fmt(r.w2)}</span><span>{fmt(r.w3)}</span><span className="tv-total">{fmt(r.total)} <i className={r.change>0?'up':r.change<0?'down':''}>{r.change>0?'▲ '+r.change:r.change<0?'▼ '+Math.abs(r.change):'—'}</i></span></div>)}</div><div className="tv-footer"><span>{m?.course_name||'Tom Krise 19th Hole Golf Simulator'}</span><span>LIVE LEADERBOARD</span></div></div>
}
