'use client'
import {useEffect,useState} from 'react'
import {supabase} from '@/lib/supabase'
import MonthlySetup from '../monthly-setup';import WeeklyScoring from '../weekly-scoring';import Week4Cup from '../week4-cup';import RawScoreHistory from '../raw-score-history'
import {AdminDenied,AdminFrame,useAdminGuard} from '../admin-shared'
type Team={id:string;name:string};type Player={id:string;team_id:string|null;full_name:string}
type Panel='setup'|'scores'|'cup'|'history'
export default function LeagueAdmin(){const guard=useAdminGuard();const [seasonId,setSeasonId]=useState(''),[scoreCap,setScoreCap]=useState(30),[capDraft,setCapDraft]=useState('30'),[capMsg,setCapMsg]=useState(''),[teams,setTeams]=useState<Team[]>([]),[players,setPlayers]=useState<Player[]>([]),[panel,setPanel]=useState<Panel>('setup');useEffect(()=>{if(!guard.admin)return;(async()=>{const {data:s}=await supabase.from('seasons').select('id,standings_score_cap').eq('is_active',true).eq('is_closed',false).limit(1).maybeSingle();if(!s?.id)return;setSeasonId(s.id);const cap=Number(s.standings_score_cap||30);setScoreCap(cap);setCapDraft(String(cap));const {data:t}=await supabase.from('teams').select('id,name').eq('season_id',s.id).eq('is_active',true).order('name');setTeams((t||[]) as Team[]);const ids=(t||[]).map(x=>x.id);const {data:p}=ids.length?await supabase.from('players').select('id,team_id,full_name').in('team_id',ids).eq('is_active',true).order('created_at'):({data:[]} as any);setPlayers((p||[]) as Player[])})()},[guard.admin]);async function saveScoreCap(){const cap=Number(capDraft);if(!Number.isFinite(cap)||cap<=0){setCapMsg('Enter a valid standings score cap greater than 0.');return}const {error}=await supabase.from('seasons').update({standings_score_cap:cap}).eq('id',seasonId);if(error){setCapMsg(error.message);return}setScoreCap(cap);setCapMsg(`Standings score cap saved at ${cap.toFixed(1)}.`)}
if(!guard.ready || !guard.admin)return <AdminDenied {...guard}/>;return <AdminFrame title="League Setup & Scoring" description="Choose one league task at a time for a cleaner, easier scoring workspace."><div className="card standings-cap-admin-v1332"><div><h2>Standings Score Cap</h2><p className="muted">Maximum score that counts for weekly standings and Week 4 head-to-head results. Raw scores and all-time team statistics remain uncapped.</p></div><div className="standings-cap-control-v1332"><label className="field">Maximum Standing Score<input type="number" min="0.1" step="0.1" value={capDraft} onChange={e=>setCapDraft(e.target.value)}/></label><button className="btn" onClick={saveScoreCap}>Save Score Cap</button></div>{capMsg&&<p className="message">{capMsg}</p>}</div><div className="league-admin-tabs-v1238" role="tablist" aria-label="League admin sections"><button className={panel==='setup'?'active':''} onClick={()=>setPanel('setup')}><span>1</span><strong>Monthly Setup</strong><small>Course, handicap & setup</small></button><button className={panel==='scores'?'active':''} onClick={()=>setPanel('scores')}><span>2</span><strong>Weekly Scoring</strong><small>Enter weekly results</small></button><button className={panel==='cup'?'active':''} onClick={()=>setPanel('cup')}><span>3</span><strong>Week 4 & Cup</strong><small>Match play & Cup points</small></button><button className={panel==='history'?'active':''} onClick={()=>setPanel('history')}><span>4</span><strong>Raw Score History</strong><small>Historical team scores</small></button></div><div className="league-admin-workspace-v1238">{panel==='setup'&&<MonthlySetup seasonId={seasonId} teams={teams} players={players}/>} {panel==='scores'&&<WeeklyScoring seasonId={seasonId} teams={teams} scoreCap={scoreCap}/>} {panel==='cup'&&<Week4Cup seasonId={seasonId} teams={teams} scoreCap={scoreCap}/>} {panel==='history'&&<RawScoreHistory/>}</div></AdminFrame>}
