'use client'
import {useEffect,useMemo,useState} from 'react'
import {PlayerPage} from '@/components/PlayerMobileChrome'
import {supabase} from '@/lib/supabase'

type Ctx={userId:string;teamId:string;teamName:string;monthId:string;monthLabel:string;week:number;handicap:number;bonusHoles:number[];bonusValue:number;players:string[];existing?:any}
const pts=(score:number,par:number)=>{const d=score-par;return d<=-3?5:d===-2?4:d===-1?3:d===0?2:d===1?1:0}
export default function SubmitScore(){
 const [ctx,setCtx]=useState<Ctx|null>(null),[scores,setScores]=useState<(number|null)[]>(Array(18).fill(null)),[pars,setPars]=useState<(number|null)[]>(Array(18).fill(null)),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[reading,setReading]=useState(false),[msg,setMsg]=useState(''),[saving,setSaving]=useState(false)
 useEffect(()=>{if(!(window as any).Tesseract&&!document.querySelector('script[data-score-ocr]')){const sc=document.createElement('script');sc.src='https://cdn.jsdelivr.net/npm/tesseract.js@6/dist/tesseract.min.js';sc.async=true;sc.dataset.scoreOcr='1';document.head.appendChild(sc)};(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:p}=await supabase.from('profiles').select('player_id,status').eq('id',user.id).single();if(!p?.player_id){setMsg('Your account must be linked to a league player before submitting a score.');return}const {data:pl}=await supabase.from('players').select('team_id,teams(name)').eq('id',p.player_id).single();const teamId=pl?.team_id;if(!teamId)return;const {data:season}=await supabase.from('seasons').select('id').eq('is_active',true).eq('is_closed',false).maybeSingle();if(!season)return;const {data:months}=await supabase.from('league_months').select('*').eq('season_id',season.id).order('month_start');const now=new Date(), key=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;const m=(months||[]).find((x:any)=>String(x.month_start).startsWith(key))||(months||[])[0];if(!m)return;const [{data:subs},{data:weekly},{data:h},{data:roster}]=await Promise.all([supabase.from('round_score_submissions').select('*').eq('league_month_id',m.id).eq('team_id',teamId),supabase.from('weekly_scores').select('week_number').eq('league_month_id',m.id).eq('team_id',teamId),supabase.from('monthly_team_handicaps').select('handicap_points').eq('league_month_id',m.id).eq('team_id',teamId).maybeSingle(),supabase.from('players').select('full_name').eq('team_id',teamId).eq('is_active',true).order('full_name')]);const done=new Set([...(subs||[]).filter((x:any)=>x.status!=='rejected').map((x:any)=>x.week_number),...(weekly||[]).map((x:any)=>x.week_number)]);let week=[1,2,3,4].find(w=>!done.has(w))||4;const existing=(subs||[]).find((x:any)=>x.week_number===week);setCtx({userId:user.id,teamId,teamName:(pl as any)?.teams?.name||'My Team',monthId:m.id,monthLabel:new Date(m.month_start+'T12:00:00').toLocaleString('en-US',{month:'long'}),week,handicap:Number(h?.handicap_points||0),bonusHoles:[Number(m.bonus_hole_1),Number(m.bonus_hole_2)],bonusValue:Number(m.bonus_birdie_value||0.1),players:(roster||[]).map((x:any)=>x.full_name),existing})})()},[])
 const sf=useMemo(()=>scores.slice(0,10).map((s,i)=>s&&pars[i]?pts(s,pars[i]!):0),[scores,pars]);const raw=sf.reduce<number>((a,b)=>a+b,0);const bonusBirdies=ctx?ctx.bonusHoles.filter(h=>scores[h-1]&&pars[h-1]&&scores[h-1]===pars[h-1]!-1).length:0;const bonus=bonusBirdies*(ctx?.bonusValue||0);const official=raw+bonus+(ctx?.handicap||0)
 async function choose(f:File){setFile(f);setPreview(URL.createObjectURL(f));setReading(true);setMsg('Reading GSPro scorecard…');try{const T=(window as any).Tesseract;if(!T)throw new Error('OCR is still loading');const r=await T.recognize(f,'eng');const lines=r.data.text.split(/\n/).map((x:string)=>x.trim()).filter(Boolean);const numberLines:number[][]=lines.map((l:string)=>(l.match(/\b(?:[1-9]|1\d|2\d)\b/g)||[]).map(Number)).filter((a:number[])=>a.length>=10);if(numberLines.length){const parLine=numberLines.find((a:number[])=>a.slice(0,10).every((n:number)=>n>=3&&n<=5));const scoreLine=numberLines.find((a:number[])=>a!==parLine&&a.slice(0,10).every((n:number)=>n>=1&&n<=12));if(parLine)setPars(Array.from({length:18},(_,i)=>parLine[i]??null));if(scoreLine)setScores(Array.from({length:18},(_,i)=>scoreLine[i]??null));setMsg('Automatic reading complete. Please check every score before submitting.')}else setMsg('I could not confidently read the grid. Please enter the scores below; the photo will still be attached.')}catch{setMsg('Automatic reading was not confident enough. Please enter the scores below.')}finally{setReading(false)}}
 async function submit(){if(!ctx||!file)return;if(scores.slice(0,10).some(x=>!x)||pars.slice(0,10).some(x=>!x)){setMsg('Please confirm the scores and pars for holes 1–10.');return}setSaving(true);setMsg('');const ext=file.name.split('.').pop()||'jpg',path=`${ctx.userId}/${ctx.monthId}-${ctx.teamId}-w${ctx.week}-${Date.now()}.${ext}`;const up=await supabase.storage.from('round-scorecards').upload(path,file,{upsert:false});if(up.error){setMsg(up.error.message);setSaving(false);return}const row={league_month_id:ctx.monthId,team_id:ctx.teamId,week_number:ctx.week,submitted_by:ctx.userId,image_path:path,hole_scores:scores,hole_pars:pars,stableford_points:sf,raw_stableford:raw,bonus_birdies:bonusBirdies,bonus_points:bonus,handicap_points:ctx.handicap,official_total:official,status:'pending'};const {error}=await supabase.from('round_score_submissions').upsert(row,{onConflict:'league_month_id,team_id,week_number'});setMsg(error?error.message:'Scorecard submitted. It is now awaiting admin approval.');setSaving(false)}
 if(!ctx)return <PlayerPage title="Submit Score"><div className="simple-mobile-page"><h1>Submit Score</h1><p>{msg||'Loading your round…'}</p></div></PlayerPage>
 if(ctx.existing?.status==='pending')return <PlayerPage title="Submit Score"><div className="simple-mobile-page"><h1>Submit Score</h1><div className="card"><h2>{ctx.teamName}</h2><p>{ctx.monthLabel} · Week {ctx.week}</p><h3>Awaiting Admin Approval</h3><p>Your scorecard has been submitted. You can return here to check its status.</p></div></div></PlayerPage>
 return <PlayerPage title="Submit Score"><div className="simple-mobile-page submit-score-page"><h1>Submit Score</h1><div className="card"><h2>{ctx.teamName}</h2><p><strong>{ctx.monthLabel} · Week {ctx.week}</strong></p><p className="muted">Take a clear photo of the final GSPro scorecard. The app will try to read it automatically, then you confirm the numbers.</p><label className="btn score-photo-btn">📷 Take / Upload Scorecard Photo<input hidden type="file" accept="image/*" capture="environment" onChange={e=>e.target.files?.[0]&&choose(e.target.files[0])}/></label>{preview&&<img className="score-preview" src={preview} alt="Scorecard preview"/>}{msg&&<p className="message">{msg}</p>}</div>{file&&<div className="card"><h2>Verify Scores</h2><p className="muted">Correct anything the automatic reader missed before submitting.</p><div className="score-entry-grid"><b>Hole</b><b>Par</b><b>Score</b><b>Pts</b>{Array.from({length:18},(_,i)=><div className="score-entry-row" key={i}><span>{i+1}{ctx.bonusHoles.includes(i+1)?' ★':''}</span><input inputMode="numeric" value={pars[i]??''} onChange={e=>setPars(v=>v.map((x,j)=>j===i?(e.target.value?Number(e.target.value):null):x))}/><input inputMode="numeric" value={scores[i]??''} onChange={e=>setScores(v=>v.map((x,j)=>j===i?(e.target.value?Number(e.target.value):null):x))}/><strong>{i<10&&scores[i]&&pars[i]?pts(scores[i]!,pars[i]!):ctx.bonusHoles.includes(i+1)&&scores[i]&&pars[i]&&scores[i]===pars[i]!-1?`+${ctx.bonusValue}`:'—'}</strong></div>)}</div><div className="round-calc"><p>Raw Stableford <b>{raw}</b></p><p>Bonus Birdies <b>{bonusBirdies} (+{bonus.toFixed(1)})</b></p><p>Monthly Handicap <b>{ctx.handicap>=0?'+':''}{ctx.handicap.toFixed(1)}</b></p><p className="official">Calculated Round Score <b>{official.toFixed(1)}</b></p></div><button className="btn" disabled={saving||reading} onClick={submit}>{saving?'Submitting…':'✓ Scores Are Correct — Submit'}</button></div>}</div></PlayerPage>
}
